services:
  database:
    ports:
      - "33061:3306"
# ... other services like mailer, mercure port exposure
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mercure:
    ports:
      - "9090:80" # Example: exposing Mercure on host port 9090